### PR TITLE
ercolorspace: Properly transform caps to only allow format combinations ...

### PR DESCRIPTION
**Pull request by sdroege**
...we can handle

https://github.com/EricssonResearch/openwebrtc-gst-plugins/issues/25

### CODE REVIEW

**Comment by stefanalund** [comment]
Getting closer :) The video on the other side (Chrome) is black and there is an error message that I will post later. 

image

**Comment by stefanalund** [comment]
```
409:gst_inter_video_src_create:<source-1>[00m Failed to negotiate caps video/x-raw, format=(string)BGRA, width=(int)640, height=(int)480, pixel-aspect-ratio=(fraction)1/1, interlace-mode=(string)progressive, colorimetry=(string)sRGB, framerate=(fraction)30/1
==== Error message start ====
Error in element source-1.
Error: Internal data flow error.
Debugging info: gstbasesrc.c(2943): void gst_base_src_loop(GstPad *) (): /GstPipeline:transport-agent-1/GstBin:source-bin-1/GstInterVideoSrc:source-1:
streaming task paused, reason not-negotiated (-4)
==== Error message stop ====
```

**Comment by superdump** [comment]
As a note, that black and white checkerboard bug looks like an old bug in libvpx we had last year.

**Comment by superdump** [comment]
Maybe we need to check the cerbero libvpx build against our build scripts in case there's a workaround/fix that is needed. I seem to remember something about compiler optimisations.

**Comment by sdroege** [comment]
Ah, interesting. @nirbheek, can you check the cerbero libvpx build settings against the one from the build scripts?

**Comment by stefanalund** [comment]
These kind of video images are not always present. Most of the time I only get black frames.

**Comment by superdump** [comment]
Here it is: https://code.google.com/p/webm/issues/detail?id=603

**Comment by nirbheek** [comment]
I've pushed the change: https://github.com/nirbheek/cerbero/commit/86df1d951783aad7c83ff6cece1020cc6a712069

@sdroege I think this can go to upstream Cerbero as well since it's not specific to OWRTC.

**Comment by stefanalund** [comment]
Still black frames after updating to latest Cerbero.

**Comment by nirbheek** [comment]
I need to see if the configure option was actually added; can you give me the contents of:

~/cerbero/logs/ios*/libvpx-configure.log ? We can continue this on IRC to avoid polluting this bug.

**Comment by sdroege** [comment]
The black frames have other reasons, there are multiple broken things currently :) libvpx part should just produce funny looking pictures

**Pull request merged**
