### PR TITLE
Part of fixing interop with FF nightly and DevEd

### PR DESCRIPTION
**Pull request by stefhak**
Depends on https://github.com/EricssonResearch/openwebrtc-build-scripts/pull/34

I've not tested anything more than FF - OWR interop on OSX. More tests should be done on more platforms before landing.
I don't know what the commit "tag file identifying the build script that installed the sources" really does. I did not do that commit manually anyway.

### CODE REVIEW

**Comment by sdroege** [comment]
Makes sense :+1:

**Comment by sdroege** [comment]
Does this require the new openssl version?

**Comment by stefhak** [comment]
Yes, this is only supported in 1.0.2 (and presumably later versions). According to https://www.openssl.org/docs/ssl/SSL_set_ecdh_auto.html

**Comment by sdroege** [comment]
Thanks, also merged.

**Pull request closed without merging**
